# This script was generated by AI

# install.packages(c("tidycensus","tidyverse"))
library(tidycensus)
library(tidyverse)

# 1) Set your key (once per session)
# census_api_key("<YOUR_CENSUS_KEY>", install = FALSE)

year <- 2023   # latest ACS 5-year currently available for counties
survey <- "acs5"

# 2) Fetch tract-level B17001 for Arkansas, wide format
ar_b17001 <- get_acs(
  geography = "tract",
  state = "AR",
  year = year,
  survey = survey,
  table = "B17001",
  output = "wide",
  cache_table = TRUE
)



ar_b17001 |> 
  write_csv("toy-data/child-poverty-ar.csv")
